//! Correctness gate: every fixture row generated by `scripts/gen-fixtures.mjs`
//! from the reference `adhan` npm package must match the Rust port within
//! ±60 seconds per prayer time.

use athan::prayer_times::{
    CalculationMethod, Coordinates, Madhab, PrayerTimes,
};
use chrono::{DateTime, NaiveDate, Utc};
use serde::Deserialize;

#[derive(Debug, Deserialize)]
struct FixtureRow {
    method: String,
    madhab: String,
    lat: f64,
    lng: f64,
    date: String,
    fajr: Option<String>,
    sunrise: Option<String>,
    dhuhr: Option<String>,
    asr: Option<String>,
    maghrib: Option<String>,
    isha: Option<String>,
}

fn parse_iso(s: &str) -> DateTime<Utc> {
    DateTime::parse_from_rfc3339(s)
        .expect("fixture ISO timestamp must parse")
        .with_timezone(&Utc)
}

fn check_prayer(
    label: &str,
    expected: &Option<String>,
    actual: Option<DateTime<Utc>>,
    failures: &mut Vec<String>,
) {
    match (expected, actual) {
        (None, None) => {}
        (Some(expected), Some(actual)) => {
            let expected = parse_iso(expected);
            let diff = (actual - expected).num_seconds().abs();
            if diff > 60 {
                failures.push(format!(
                    "{label}: expected {expected}, got {actual} (diff {diff}s)"
                ));
            }
        }
        (None, Some(actual)) => {
            failures.push(format!("{label}: expected uncomputable (null), got {actual}"));
        }
        (Some(expected), None) => {
            failures.push(format!("{label}: expected {expected}, got uncomputable (None)"));
        }
    }
}

#[test]
fn matches_adhan_js_fixtures() {
    let json = include_str!("fixtures.json");
    let rows: Vec<FixtureRow> = serde_json::from_str(json).expect("fixtures.json must parse");
    assert_eq!(rows.len(), 12 * 2 * 5 * 5, "unexpected fixture row count");

    let mut failures = Vec::new();

    for row in &rows {
        let method = CalculationMethod::from_name(&row.method)
            .unwrap_or_else(|| panic!("unknown method {}", row.method));
        let mut params = method.parameters();
        params.madhab = match row.madhab.as_str() {
            "Shafi" => Madhab::Shafi,
            "Hanafi" => Madhab::Hanafi,
            other => panic!("unknown madhab {other}"),
        };

        let date = NaiveDate::parse_from_str(&row.date, "%Y-%m-%d").expect("fixture date parses");
        let coordinates = Coordinates::new(row.lat, row.lng);
        let times = PrayerTimes::new(coordinates, date, params);

        let label = |prayer: &str| {
            format!(
                "{} {} ({},{}) {} {prayer}",
                row.method, row.madhab, row.lat, row.lng, row.date
            )
        };

        check_prayer(&label("fajr"), &row.fajr, times.fajr, &mut failures);
        check_prayer(&label("sunrise"), &row.sunrise, times.sunrise, &mut failures);
        check_prayer(&label("dhuhr"), &row.dhuhr, times.dhuhr, &mut failures);
        check_prayer(&label("asr"), &row.asr, times.asr, &mut failures);
        check_prayer(&label("maghrib"), &row.maghrib, times.maghrib, &mut failures);
        check_prayer(&label("isha"), &row.isha, times.isha, &mut failures);
    }

    assert!(
        failures.is_empty(),
        "{} prayer-time mismatches:\n{}",
        failures.len(),
        failures.join("\n")
    );
}
